### ISSUE TITLE
Upstart script not valid for >= v 0.14

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/ansible-opentripplanner#12]
The command-line parameters have changed in the latest release of OTP; the current upstart script will not work with version 0.14 or later.

**Comment by hectcastro** [comment]
Did this get resolved? I saw that 0.15 is the default now.

**Comment by flibbertigibbet** [comment]
No. We have not yet changed the version in use by [cac-tripplanner](https://github.com/azavea/cac-tripplanner), which is the only project actively using this role currently, and which will be upgraded to a newer OTP when we do further work on it.

**Comment by flibbertigibbet** [comment]
Closed in #16
